---
ID: "7b1dd36b-6e52-488c-9adc-57fda6c98a69"
Parent: "53fbbb98-b2a1-4cf3-ad00-2203bb1a8f67"
Template: "53fbbb98-b2a1-4cf3-ad00-2203bb1a8f67"
Path: /sitecore/templates/Foundation/Grid/Cell Size/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180206T063651Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
