---
ID: "28684916-75e4-45de-8d1f-ec57a17eb10d"
Parent: "f4862d8a-ef6a-411c-ab9d-abfe5ed83ba7"
Template: "f4862d8a-ef6a-411c-ab9d-abfe5ed83ba7"
Path: /sitecore/templates/Foundation/Grid/RenderingParameters_Spacing/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180308T235547Z
