---
ID: "e64a6b39-504f-4e66-9f2a-c7c265270448"
Parent: "a405650c-69c5-4811-b8b3-f39ea9c1a14f"
Template: "a405650c-69c5-4811-b8b3-f39ea9c1a14f"
Path: /sitecore/templates/Foundation/Grid/RenderingParameters_Grid/__Standard Values
DB: master
SharedFields:
- ID: "3094d236-5985-4c4f-ae6a-e30740885532"
  Hint: Caching
  Value: 0|0|0|0|0|0|0|0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180207T213111Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "c96ba6b4-3ea6-44b5-ac1f-4c064fe17ab8"
      Hint: CellAlignment
      Value: left
